### ISSUE TITLE
Ignition 8.1 - Tag real-time override is missing

### ISSUE THREAD

**Issue by alexjhawk** [hms-networks/IgnitionEwonConnector#112]
While the code remains for adding a real-time override to each tag added by the Ignition Ewon Connector, they do not show up. This completely disables/breaks the individual tag real-time override functionality.

**Comment by alexjhawk** [comment]
Unfortunately, this commit did not fully fix the issue. After a day of testing without any issues, adding a new tag on the device seems to have completely broken this functionality again. Every tag throws the same error:

```
java.lang.Exception: Tag configuration not found for tag path ah-flexy/TagTest002a

at com.hms_networks.americas.sc.ignition.SyncManager.createRealtimePropertyForTag(SyncManager.java:1071)

at com.hms_networks.americas.sc.ignition.SyncManager.updateTagValues(SyncManager.java:866)

at com.hms_networks.americas.sc.ignition.SyncManager.syncLatestValues(SyncManager.java:578)

at com.hms_networks.americas.sc.ignition.SyncManager.executeSync(SyncManager.java:513)

at com.hms_networks.americas.sc.ignition.SyncManager.run(SyncManager.java:311)

at com.inductiveautomation.ignition.common.execution.impl.BasicExecutionEngine$TrackedTask.run(BasicExecutionEngine.java:582)

at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)

at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)

at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by alexjhawk** [comment]
This has been re-resolved by disabling the check for the tag configuration type. The realtime property is occasionally not loaded/updated because the tag configuration returned has a unknown type, but after testing, the unknown type still works properly and creates what we need.
